### ISSUE TITLE
feat: support zk c client

### ISSUE THREAD

**Issue by GehaFearless** [pegasus-kv/pegasus-docker#13]
two requests：
**~~As I build rdsn with docker ubuntu1804, failed at building thirdparty hadoop.~~**
I notice there is no JAVA_HOME in the environment.
Unubtu solved by https://github.com/pegasus-kv/pegasus-docker/pull/10
Centos not solved

**support for zk kerberos**
https://github.com/apache/incubator-pegasus/issues/847
As I build zk c client, I need cppunit for autoreconf.

PR: https://github.com/pegasus-kv/pegasus-docker/pull/14

**Comment by GehaFearless** [comment]
Could I increase these?

For Unubtu:
~~apt-get install libcppunit-dev libcppunit-doc~~
apt-get install libkrb5-dev libsasl2-dev

For Centos:
~~yum install cppunit-devel  netcat~~
yum install krb5-devel cyrus-sasl-devel

update maven to 3.8.3

**Comment by neverchanje** [comment]
zookeeper-c-client supports a compile option `-D WANT_CPPUNIT=OFF` to skip building unit tests, and thereby you won't need to install cppunit. 

https://github.com/apache/zookeeper/blob/master/zookeeper-client/zookeeper-client-c/CMakeLists.txt Refer the cmake file for details.

**Comment by GehaFearless** [comment]
> zookeeper-c-client supports a compile option `-D WANT_CPPUNIT=OFF` to skip building unit tests, and thereby you won't need to install cppunit.
> 
> https://github.com/apache/zookeeper/blob/master/zookeeper-client/zookeeper-client-c/CMakeLists.txt Refer the cmake file for details.

https://github.com/apache/zookeeper/blob/master/zookeeper-client/zookeeper-client-c/README.
Look this,  you should execute autoreconf if you want get libzookeeper_mt. And execute autoreconf depend on cppunit. So I do it.

**Comment by GehaFearless** [comment]
> > zookeeper-c-client supports a compile option `-D WANT_CPPUNIT=OFF` to skip building unit tests, and thereby you won't need to install cppunit.
> > https://github.com/apache/zookeeper/blob/master/zookeeper-client/zookeeper-client-c/CMakeLists.txt Refer the cmake file for details.
> 
> https://github.com/apache/zookeeper/blob/master/zookeeper-client/zookeeper-client-c/README. Look this, you should execute autoreconf if you want get libzookeeper_mt. And execute autoreconf depend on cppunit. So I do it.

Now, I find new way to bypass cppunit
